mcc: '262'
mnc: '98'
cell:
nci: '0x000000011'
idLength: 32
tac: 1
cellBarred: false


linkIp: gnb2.ueransim.org
ngapIp: gnb2.ueransim.org
gtpIp: gnb2.ueransim.org

amfConfigs:
  - address: amf.open5gs.org
    port: 38412

slices:
  - sst: 1
    sd: 1

ignoreStreamIds: true

# Custom parameter to document the file share path
fileSharePath: /shared